name: deploy-gh-pages
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Generate
        run: yarn install && yarn storybook-build
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./storybook/static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}